-- Tala Backend PostgreSQL Initialization
-- Create databases for development and test
-- Note: CREATE DATABASE IF NOT EXISTS is not supported in PostgreSQL
-- The main database tala_db is created by the POSTGRES_DB env var

-- Connect to tala_db
\c tala_db

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "btree_gin";

-- Create schemas
CREATE SCHEMA IF NOT EXISTS events;
CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS ai;
CREATE SCHEMA IF NOT EXISTS reminders;
CREATE SCHEMA IF NOT EXISTS media;
CREATE SCHEMA IF NOT EXISTS files;
CREATE SCHEMA IF NOT EXISTS origin_data;

-- Grant privileges to tala user
GRANT ALL PRIVILEGES ON SCHEMA events TO tala;
GRANT ALL PRIVILEGES ON SCHEMA users TO tala;
GRANT ALL PRIVILEGES ON SCHEMA analytics TO tala;
GRANT ALL PRIVILEGES ON SCHEMA ai TO tala;
GRANT ALL PRIVILEGES ON SCHEMA reminders TO tala;
GRANT ALL PRIVILEGES ON SCHEMA media TO tala;
GRANT ALL PRIVILEGES ON SCHEMA files TO tala;
GRANT ALL PRIVILEGES ON SCHEMA origin_data TO tala;

-- Note: Tables, indexes, and triggers are created by Flyway migrations
-- This init.sql only sets up extensions, schemas, and permissions

-- Grant table privileges
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA events TO tala;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA users TO tala;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics TO tala;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ai TO tala;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA reminders TO tala;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA media TO tala;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA files TO tala;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA origin_data TO tala;

-- Grant sequence privileges
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA events TO tala;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA users TO tala;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA analytics TO tala;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ai TO tala;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA reminders TO tala;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA media TO tala;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA files TO tala;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA origin_data TO tala;
